### ISSUE TITLE
alyx posting weights/water

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/alyx-matlab#15]
Alyx is not receiving weights consistnently.
Also water is not posting properly for all mice -trained volumer received (sometimes twice, sometimes not at all).
Also there are big gaps in the subject history weights/water history- seee 'Nyx' etc.

We need to be sure that data is safe in Alyx and that it won't suffenly decide to forget prior history.

Warning: JSON command failed - saved in queue 
> In alyx.flushQueue (line 54)
  In alyx.postData (line 28)
  In alyx.postWater (line 27)
  In eui.ExpPanel/expStopped (line 224)
  In eui.ExpPanel>@(varargin)p.expStopped(varargin{:}) (line 84)
  In srv.StimulusControl/onWSReceived (line 189)
  In srv.StimulusControl>@(varargin)obj.onWSReceived(varargin{:}) (line 163)

**Comment by nsteinme** [comment]
refresh all websites, logout and login in matlab - this is almost certainly
because I restarted things this afternoon while you were in the middle of
working. Posting weights working fine for me. Please check that the water
control sheet for nyx doesn't have any weird formatting issues, I can look
later.

**Comment by laurax452** [comment]
(this is andy) I fixed 1/2 of this problem - there was an issue for queuing where the first queued command was a failure but the second was a failure, I made a pull request on github. 

the second error is related to the JSON command, it's trying to post a water administration but it says that it needs a valid number and it's not being given one. I don't know what alyx is expecting or if this JSON command is off, can you look at this and see if it's not in the correct format or something? 
water-administrations
{
	"subject": "ALK047",
	"water_administered": [
		[0.5075],
		[0]
	],
	"date_time": "2017-05-15T15:28:16",
	"hydrogel": 0,
	"user": "laura"
}

**Comment by nsteinme** [comment]
water administered certainly cannot be a vector - looks like that's what
you've done there. If this was auto-posted by miles's code, then you know
who to ask about it... @k1o0

**Comment by nsteinme** [comment]
I think this was related to the particular water posting code, and has been resolved. Please re-open if it occurs again.
