### ISSUE TITLE
Subject history view

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/alyx-matlab#17]
Subject history in the matlab eGUI is very useful for monitoring the mice/water/weights.
It would be nice if there were additional columns for water min and excess water given (as in sheets).
Also it would be great if the weight plot was more like the database, with the orange/red lines.
Also it would be nice if the subject history was named (e.g. Vin instead of Figure 3) for when you are looking at multiple mice.

**Comment by nsteinme** [comment]
Thanks, very much agreed, I'll do this if/when I can. @k1o0 are you interested in trying to implement these? Naming the figure is easy, but getting the orange/red lines will be harder, we'll have to talk about it.

**Comment by k1o0** [comment]
Nick did a beautiful job on this.  Resolved.
