### ISSUE TITLE
Queue suggestions

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx-matlab#19]
Sorry, just got to read this queueing system.

It's worth noting that...

200 error codes are all successes so nothing needs to be queued
300 error codes shouldn't be queued. They're redirects
400 error codes must not be queued either - they're supposed to indicate a user error (wrong type of data, no endpoint available blah blah blah)
500 error codes *should* normally be queued as they indicate a server error.

In essence I'd check for a 5xx code (probably not a 511 but we're not using those yet) or a network timeout. But don't queue in case of 3xx or 4xx codes.

**Comment by nippoo** [comment]
http://www.restapitutorial.com/httpstatuscodes.html

**Comment by petersaj** [comment]
thanks! you're working on alyx from china??

updated flushQueue for these http codes and made a pull request (by the way: when something gets updated, do people in lab know to pull the newest versions?)

**Comment by nsteinme** [comment]
andy implemented this nicely - closing -
