### ISSUE TITLE
Error using cellfun on 's'

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx-matlab#20]
This is an error in both 2016b and 2017a.  I'm using the most recent version of Rigbox, etc.  Is Alyx now returning data differently?

`Error using cellfun
Input #2 expected to be a cell array, was struct instead.

Error in eui.AlyxPanel/alyxLogin (line 120)
                respUser = cellfun(@(x)x.responsible_user, s, 'uni', false);

Error in eui.AlyxPanel>@(src,evt)alyxLogin(obj) (line 23)
    'Callback', @(src, evt)alyxLogin(obj));
 
Error while evaluating UIControl Callback.`

**Comment by rossant** [comment]
might be fixed now

**Comment by nsteinme** [comment]
I think this was fixed with rest-api repairs, let me know if it occurs again.
