### ISSUE TITLE
passwordUI missing

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx-matlab#25]
Running alyx.loginWindow, I get 

`Undefined function or variable 'passwordUI'.

Error in alyx.loginWindow (line 33)
    pwd = passwordUI();`

Does it refer to this? http://uk.mathworks.com/matlabcentral/fileexchange/29616-passwordui

If so,  should we add it to the repository?

**Comment by nsteinme** [comment]
The function is in alyx-matlab/helpers - I think you didn't add the path correctly - it needs to include subfolders, so do "addpath(genpath('/my/github/path/alyx-matlab'))"

**Comment by kdharris101** [comment]
Thanks, yes it works now
