### ISSUE TITLE
Upon invalid token on all functions, return loginwindow

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx-matlab#4]
So when the token expires you get prompted to re-log-in

**Comment by nsteinme** [comment]
The problem with this would be for code that runs on the experiment server
computer, where you don't want it popping up any windows... not sure what
the best approach is.

**Comment by nippoo** [comment]
Pass it an optional `headless = True` or `no-prompt` flag or whatever.

Either way, here you just want to pass the tokens to the experiment server from MC on the user's computer.

Max

**Comment by k1o0** [comment]
I can implement this, however I need to know what message/status code is returned when the token is invalid...
