### ISSUE TITLE
Subject History display error (computer specific)-Jai

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/alyx-matlab#47]
The left-hand computer in the training room does not not display the 'Subject History' window  properly. 

![MVIMG_20190614_125928](https://user-images.githubusercontent.com/27958601/59683150-8230ba00-91cf-11e9-9e00-20843b016294.jpg)

Expanding does not help:
![MVIMG_20190614_125943](https://user-images.githubusercontent.com/27958601/59683344-e94e6e80-91cf-11e9-9b97-3cd4f7071d20.jpg)

You can see that the graphs are also in the wrong order.
I assume it is something specific to that computer perhaps the graphics card or software issue but it would be good to fix it sometime soon.

This is how it should look:
![MVIMG_20190614_130104](https://user-images.githubusercontent.com/27958601/59683548-44806100-91d0-11e9-88ac-a1a36e6425a6.jpg)

I assume this would be best fixed by someone physically in the lab.

**Comment by jaib1** [comment]
Hey Laura, yup this was a graphics driver issue. New driver installed, as well as two new monitors for the 'mc' computers in the behavior room.
