### ISSUE TITLE
add HTTPS for everything

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx-matlab#8]
must not use HTTP since we're now over the public web

**Comment by nsteinme** [comment]
Does this literally mean replacing instances of http with https or is there
something more to do?

**Comment by nippoo** [comment]
We can't close this yet - upon testing (specify https:// to test it manually) the root Let's Encrypt cert isn't trusted by this version of Java. Java has included the right intermediate certificate in the latest version but clearly Matlab doesn't come bundled with it (?). Need to find a way to generate / extract the cert and manually add to trusted intermediates. Googling the error returns some helpful results
